version: "3.1"

# Services
services:

  # Apache + PHP
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> e7eba53 (prueba)
  videoclub:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: 'videoclub'
<<<<<<< HEAD
=======
  apache_php_phpini:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: 'Videoclub'
>>>>>>> 431e3b5799488f2300bc65e2a8c70f0d14678b3b
=======
>>>>>>> e7eba53 (prueba)
    volumes:
      - ./src/:/var/www/html
      - ./.docker/php.ini:/usr/local/etc/php/php.ini
    expose:
      - 80
    ports:
      - '80:80'

# Lanzar con
# docker-compose up -d

# Ver los logs con
# docker-compose logs -f
